/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAuth {
    }
    interface AppHome {
    }
    interface AppMenu {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface AppTabDashboard {
    }
    interface AppTabHome {
    }
    interface AppTabs {
    }
}
declare global {
    interface HTMLAppAuthElement extends Components.AppAuth, HTMLStencilElement {
    }
    var HTMLAppAuthElement: {
        prototype: HTMLAppAuthElement;
        new (): HTMLAppAuthElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {
    }
    var HTMLAppMenuElement: {
        prototype: HTMLAppMenuElement;
        new (): HTMLAppMenuElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTabDashboardElement extends Components.AppTabDashboard, HTMLStencilElement {
    }
    var HTMLAppTabDashboardElement: {
        prototype: HTMLAppTabDashboardElement;
        new (): HTMLAppTabDashboardElement;
    };
    interface HTMLAppTabHomeElement extends Components.AppTabHome, HTMLStencilElement {
    }
    var HTMLAppTabHomeElement: {
        prototype: HTMLAppTabHomeElement;
        new (): HTMLAppTabHomeElement;
    };
    interface HTMLAppTabsElement extends Components.AppTabs, HTMLStencilElement {
    }
    var HTMLAppTabsElement: {
        prototype: HTMLAppTabsElement;
        new (): HTMLAppTabsElement;
    };
    interface HTMLElementTagNameMap {
        "app-auth": HTMLAppAuthElement;
        "app-home": HTMLAppHomeElement;
        "app-menu": HTMLAppMenuElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-tab-dashboard": HTMLAppTabDashboardElement;
        "app-tab-home": HTMLAppTabHomeElement;
        "app-tabs": HTMLAppTabsElement;
    }
}
declare namespace LocalJSX {
    interface AppAuth {
    }
    interface AppHome {
    }
    interface AppMenu {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface AppTabDashboard {
    }
    interface AppTabHome {
    }
    interface AppTabs {
    }
    interface IntrinsicElements {
        "app-auth": AppAuth;
        "app-home": AppHome;
        "app-menu": AppMenu;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-tab-dashboard": AppTabDashboard;
        "app-tab-home": AppTabHome;
        "app-tabs": AppTabs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-auth": LocalJSX.AppAuth & JSXBase.HTMLAttributes<HTMLAppAuthElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-menu": LocalJSX.AppMenu & JSXBase.HTMLAttributes<HTMLAppMenuElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-tab-dashboard": LocalJSX.AppTabDashboard & JSXBase.HTMLAttributes<HTMLAppTabDashboardElement>;
            "app-tab-home": LocalJSX.AppTabHome & JSXBase.HTMLAttributes<HTMLAppTabHomeElement>;
            "app-tabs": LocalJSX.AppTabs & JSXBase.HTMLAttributes<HTMLAppTabsElement>;
        }
    }
}
